spring.application.name=smart_shop_user

# database
spring.datasource.url=jdbc:mariadb://172.19.110.199:3306/smart_shop
spring.datasource.username=root
spring.datasource.password=root

#JPA Configuration
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.sql.init.mode=always
server.port=8081